<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPwDEsUf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPwDEsUf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPwDEsUf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPwDEsUf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPwDEsUf\App_KernelDevDebugContainer([
    'container.build_hash' => 'PwDEsUf',
    'container.build_id' => '687db2d8',
    'container.build_time' => 1680836073,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPwDEsUf');
