<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJtFWR1Y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJtFWR1Y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJtFWR1Y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJtFWR1Y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJtFWR1Y\App_KernelDevDebugContainer([
    'container.build_hash' => 'JtFWR1Y',
    'container.build_id' => '89158f51',
    'container.build_time' => 1680699955,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJtFWR1Y');
